### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Rochet2** [samutamm/katonalle#1]
Projekti ladattu 8.2.2016 klo. 15.02

Joo-o. Jotain omia apeja jossain eri repositorioissa.. jep jep. Ja kaikki javascriptillä tehty. Itse en ole käyttänyt mitään vastaavaa ainakaan samassa skaalassa. Sekavuudesta suureen määrään lisää sekavuutta.
Mutta mennään asiaan.

Kyse oli muistaakseni yhdestä PDF tiedostosta ja nyt täällä on monta :(
dokumentaatio.pdf ei ole PDF ollenkaan, vaan joku tekstitiedosto jonka pääte on vaan .pdf
Miten olisi jos muuntaisit nämä yhdeksi ja oikeaan muotoon? Tai ainakin edes oikeaan muotoon. :) Kai sen voi jättää loppunkin .. hmm.

Kaaviot näyttävät suhteellisen selkeiltä ja oikeellisilta.
Mitään .sql tiedostoa en löytänyt .. missä testidatat ja muut? :(
Joko testidataa ja tietokannan luovia tiedostoja ei ole tai toinen tai molemmat ovat hyvin lyhyet tai ne jossakin minulle käsittämättömässä muodossa. Ilmeisesti jonkin laisia "unit testejä" kuitenkin löysin - jos oikein ymmärsin.
Tästä voisi selittää vähän jossain kun kurssi muuten on PHP:llä otetutettu. Muuten joko ne tulisi tehdä tai niitä tarvitsee lisää tai ne on kunnossa - jonka varmaan itse tiedät paremmin.

Tarkoititko apartment vai apart**e**ment? Kaikkialla lukee jälkimmäinen.

Itse sivulla on aika vähän toiminnallisuutta ja sivuja. Jompaa kumpaa toivoisin itse olevan enemmän. En löytänyt missä eri sivut määritellään eikä sivuja ole navigointipalkissa eikä readme:ssa, joten en löytänyt niitä jos niitä edes oli :(
Löysin joitain viitteitä esim. /apartements/new ja vastaavia jotka näyttivät sivujen reitityksiltä, mutta herokussa ne eivät kuitenkaan toimineet. Sivuja ei siis ole tai ne eivät näy herokussa vielä.

Koodi itsessään näyttää ihan hyvältä mielestäni.

**Comment by samutamm** [comment]
Kiitos palautteesta!
Tietokannat ja sql-komennot löytyvät PersonApi ja ApartementsApi-repositorioista, mutta mallien yksikkö testit puuttuvat. Teen pikimmiten. Herokuun on myös deployatty vanha versio, päivitän senkin.
Projetini arkkitehtuuri on kieltämättä erilainen, kuin kurssilla annettu erimerkki.

Näkymät löytyvät .jsx tiedostoista React.js-luokkien joukosta. Sen sijaan, että näkymät renderöitäisiin palvelimella PHP:n(tms) kirjastoilla, palvelin lähettää selaimeen lihavan klöntin JavaScriptiä, joka muokkaa HTML-näkymää selaimessa. Näin sovellus on(/voi olla) vuorovaikutteisempi käyttäjälle.

hups, Ranskan kieli on tarttunut koodiin: apartement :D
